---
language: node_js
node_js:
  - "9"

os:
  - linux
  - osx

sudo: required
dist: trusty

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - npm install -g travis-ci-cloudfront-invalidation

script:
  - npm run lint:js
  - npm test

before_deploy:
  - npm run build
  - npm run build:production

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_DEV
    skip_cleanup: true
    local-dir: dist
    acl: public_read
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_PROD
    skip_cleanup: true
    local-dir: dist-prod
    acl: public_read
    on:
      branch: master

after_deploy:
  - if [[ $TRAVIS_BRANCH = "master" ]]; then travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_ID_PROD -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST; fi
